import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import About from '@/components/About'
import Footer from '@/components/Footer'
import Experience from '@/components/Experience'
import Work from '@/components/Work'
import Contant from '@/components/Contant'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
          <Navbar />
          <About />
          <Experience />
          <Work />
          <Contant />
          {/* <Footer /> */}
      </div>
    </>
  )
}
